server:
  port: 9082

keycloakRequiredUserRole: user_role # user must have this role to have access
keycloak:
  enabled: true # enables keycloak authentication
  auth-server-url: http://localhost:8180/auth # keycloak server address (from the docker run command)
  realm: SpringBootAngular # name of imported realm
  resource: SpringBootAngularClient # name of imported client
  security-constraints: # private resources (user with role required)
    - authRoles:
        - ${keycloakRequiredUserRole}
      securityCollections:
        - name: protected resource
          patterns:
            - /api/*
    - securityCollections: # public resources (no required role)
        - name: public resource
          patterns:
            - /api/keycloak/config
  credentials:
    secret: "b92daa5d-39ff-420e-b8fc-51561130a528" # (Clients > SpringBootAngularClient > Credentials > Secret)
  realm-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoG+YxCSIwL6ZgFxK4ir8NrUBp4yTPS3tkAbLDWR7BU1t1OCZX7YptHDBL6T3l+RQWeWl9mvihqK4BVMOHjQEqU1Oe4qWOHzQIzmoRX39W3+jy66IrVSqylGRVoRygAq8z6T00pESIlXpwOEZRo/a27/lVsFmxfGb/5EnHagDMU+9PHexIVomahzEYga72Rb03oJhoErHGhQqMPK6vyWuHWrDcgtZRmQYQ3eAfQc2MnVL69+vD+pvkZIFQ5WmIiM94toNd7V5Mz3rtzKN4ztQS9E3LhoQcU0uMBCtzti8zezuqLBbN7WMdSXjeQUjw6Sh78UYfoK7cJkN+29dyBmW7wIDAQAB"
  # (Realm Settings > Keys > Active > RSA > Public Key)

logging:
  level:
    org.keycloak.adapters: TRACE
